@URL = http://localhost:5042
GET {{URL}}/api/exercises/grouped
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Bench Press",
  "muscleGroup": "Chest",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Crunch",
  "muscleGroup": "Abs",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Bicep Curl",
  "muscleGroup": "Biceps",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Barbell Squat",
  "muscleGroup": "Legs",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Deadlift",
  "muscleGroup": "Back",
  "videoUrl": ""
}
###
# Public-domain exercise animations from JahelCuadrado/ExerciseGymGifsDB
PUT {{URL}}/api/exercises/12
Content-Type: application/json
{
  "name": "Bench Press",
  "muscleGroup": "Chest",
  "videoUrl": "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-bench-press.gif"
}
###
PUT {{URL}}/api/exercises/13
Content-Type: application/json
{
  "name": "Crunch",
  "muscleGroup": "Abs",
  "videoUrl": "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/crunch-floor.gif"
}
###
PUT {{URL}}/api/exercises/14
Content-Type: application/json
{
  "name": "Bicep Curl",
  "muscleGroup": "Biceps",
  "videoUrl": "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/barbell-curl.gif"
}
###
PUT {{URL}}/api/exercises/15
Content-Type: application/json
{
  "name": "Barbell Squat",
  "muscleGroup": "Legs",
  "videoUrl": "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-high-bar-squat.gif"
}
###
PUT {{URL}}/api/exercises/16
Content-Type: application/json
{
  "name": "Deadlift",
  "muscleGroup": "Back",
  "videoUrl": "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-deadlift.gif"
}

