@URL = http://localhost:5042
GET {{URL}}/api/exercises/grouped
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Bench Press",
  "muscleGroup": "Chest",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Crunch",
  "muscleGroup": "Abs",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Bicep Curl",
  "muscleGroup": "Biceps",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Barbell Squat",
  "muscleGroup": "Legs",
  "videoUrl": ""
}
###
POST {{URL}}/api/exercises
Content-Type: application/json
{
  "name": "Deadlift",
  "muscleGroup": "Back",
  "videoUrl": ""
}
###
# Public-domain exercise images. Each exercise has matching 0.jpg and 1.jpg frames.
PUT {{URL}}/api/exercises/12
Content-Type: application/json
{
  "name": "Bench Press",
  "muscleGroup": "Chest",
  "videoUrl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg"
}
###
PUT {{URL}}/api/exercises/13
Content-Type: application/json
{
  "name": "Crunch",
  "muscleGroup": "Abs",
  "videoUrl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg"
}
###
PUT {{URL}}/api/exercises/14
Content-Type: application/json
{
  "name": "Bicep Curl",
  "muscleGroup": "Biceps",
  "videoUrl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg"
}
###
PUT {{URL}}/api/exercises/15
Content-Type: application/json
{
  "name": "Barbell Squat",
  "muscleGroup": "Legs",
  "videoUrl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg"
}
###
PUT {{URL}}/api/exercises/16
Content-Type: application/json
{
  "name": "Deadlift",
  "muscleGroup": "Back",
  "videoUrl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg"
}
